server:
  port: 8070
  error:
    whitelabel:
      enabled: false
    path: /error


spring:
  profiles.active: dev
  jpa:
    hibernate:
      ddl-auto: "none"
      dialect: "PostgreSQLDialect"
      default_schema: "BStore"
    show-sql: true

  thymeleaf:
    prefix: classpath:/templates/

#postgres:5432/BStore
  datasource:
    url: "jdbc:postgresql://postgres:5432/BStore"
    username: "admin"
    password: "admin"
    driver-class-name: org.postgresql.Driver

  #postgres:5432/BStore
  flyway:
    url: "jdbc:postgresql://postgres:5432/BStore?ssl=false"
    user: "admin"
    password: "admin"
    locations: "classpath:/db/migration"
    baseline-on-migrate: true

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  sql:
    init:
      mode: always